# Generated by Django 4.2 on 2023-04-18 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studentID",
                    models.CharField(max_length=32, verbose_name="studentID"),
                ),
                (
                    "classname",
                    models.CharField(max_length=32, verbose_name="classname"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "starttime",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(17),
                        ],
                        verbose_name="startTime",
                    ),
                ),
                (
                    "attendance",
                    models.CharField(max_length=16, verbose_name="attendance"),
                ),
                (
                    "grade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="grade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="username")),
                ("password", models.CharField(max_length=64, verbose_name="password")),
                (
                    "accounttype",
                    models.CharField(max_length=16, verbose_name="accounttype"),
                ),
                (
                    "classname",
                    models.CharField(
                        default="ELC", max_length=32, verbose_name="classname"
                    ),
                ),
                (
                    "totalclass",
                    models.IntegerField(default=10, verbose_name="totalclass"),
                ),
                (
                    "attnumber",
                    models.IntegerField(default=0, verbose_name="attendant class"),
                ),
                (
                    "studentID",
                    models.CharField(
                        default="000", max_length=32, verbose_name="studentID"
                    ),
                ),
                (
                    "cpassword",
                    models.CharField(max_length=64, verbose_name="cpassword"),
                ),
            ],
        ),
    ]
